### ISSUE TITLE
Error installing on Docker Desktop

### ISSUE THREAD

**Issue by jldec** [projectriff/cnab-k8s-installer-base#39]
There appear to be 2 problems with installing onto k8s in Docker Desktop

1. The node name for recent Docker Desktop builds should be `docker-desktop` (see #37)
2. `localhost:6444` endpoint for talking to k8s API from inside the invocation-image container does not appear to work.

```
$ duffle install myriff riff --credentials myk8s
Executing install action...
time="2019-05-31T17:15:53Z" level=fatal msg="Get https://localhost:6443/api/v1/nodes/minikube: dial tcp 127.0.0.1:6443: connect: connection refused"
Error: Install step failed: container exit code: 1
```

**Comment by scothis** [comment]
Is `kubectl config current-context` set to minikube instead of docker-desktop?

**Comment by jldec** [comment]
No, i think the error message above (running a build of the PR #37 branch) is coming from the first detection probe check which happens to be minikube [here](https://github.com/projectriff/cnab-k8s-installer-base/blob/606626e841952e04887f14e90f9133856de5d955/pkg/kab/patch_manifest.go#L99).

**Comment by sbawaska** [comment]
The problem here is that docker-for-desktop uses `localhost` as the server address. snippet from ~/.kube/config:
```
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop-cluster
```
Since, duffle mounts this kube config inside a container when it runs the install command, our binary is unable to find a cluster at `localhost`.
minikube works because it assigns an IP address to the VM and uses that in kube config.

**Comment by sbawaska** [comment]
replacing localhost with host.docker.internal in ~/.kube/config fixes the issue, but that breaks kubectl on the host.
```
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://host.docker.internal:6443
  name: docker-desktop
```
